<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>HospitalManagement</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\HospitalManagement.Domain\HospitalManagement.Domain.csproj" />
    <ProjectReference Include="..\HospitalManagement.TestBase\HospitalManagement.TestBase.csproj" />
  </ItemGroup>

</Project>
